version: '3.3'

volumes:
    mysql:
        driver: local

services:
    php-fpm:
        build:
            context: ./docker/php-fpm
        volumes:
            - ./:/data/application:delegated
        environment:
            XDEBUG_MODE: "debug"
            XDEBUG_SESSION: bui
            PHP_IDE_CONFIG: "serverName=bui"

    nginx:
        image: nginx:alpine
        volumes:
            - ./:/data/application
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "80:80"
            - "443:443"

    mysql:
        image: mysql:8.0.17
        volumes:
            - mysql:/var/lib/mysql
        command:
            - "--sql-mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
            - "--default_authentication_plugin=mysql_native_password"
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - "3306:3306"

    node:
        build:
            context: ./docker/node
        volumes:
            - ./:/data/application
        ports:
            - "8080:8080"